### PR TITLE
Port the memory seam onto the loadable TinyMemory module (#1524 Wave 1, PR 2)

### PR DESCRIPTION
**Pull request by YellowSnnowmann**
## Summary

**Stacked on #1548** (whose two commits appear in the diff until it merges). The whole module driver of #1524, one commit per unit, dead code until the env pair `OPENCOMPANY_MEMORY=embedded` + `OPENCOMPANY_MEMORY_DRIVER=module` flips a tenant:

1. **Module host** — private tinybus broker on a process-lifetime named-thread runtime; permissive admission (strict refuses real released artifacts over the rustc string); no second host possible today (openhuman's `modules` feature is not forwarded) with the module's `SETUP_FAILED` refusal as backstop.
2. **Callbacks served before any load** (ordering is load-bearing: tinymemory installs its embedder during setup): EmbeddingHost answers one empty vector per text (NoopEmbedding-equivalent, Gate Q2 owns revisiting), ChatHost refuses via stable wire name with its request as `serde_json::Value` (no tinyagents coupling), RuntimeHost maps onto `tracing`; every detail string passes a 300-byte scrub seam (query-strip, credential redaction incl. the token *after* a Bearer marker).
3. **`ModuleMemoryProvider`** — Core/Recall/Portability forwarded member-for-member, spelled from `tinymemory_bus::names::methods::*` (typos are compile errors; the direct `tinymemory-bus` dep per the issue's review fix), over two proxies (30s interactive / 300s migrate, reasons stated); errors through the shared `wire::from_wire` table + explicit transport arms (Timeout→Timeout; NameHasNoOwner/Transport/Io/ConnectionClosed→Unreachable); **entries missing `taint` refused before decode** (serde would default them to Internal — the trusted class — failing open); narrow static advertisement passing `audit_provider` by construction; sync no-IO construction; `module` id routed in the Embedded arm beside (never aliased to) `namespace`.
4. **Delivery** — Dockerfile stage fetching the pinned v1.1.0 `ubuntu-22.04-x86_64` archive (digest verbatim from the release's checksum.toml), extracted beside its `modules.toml`, baked root-owned under `/app/modules` (uid-10001 read-only rootfs; fsGroup PVC would be refused by tinybus's ancestor walk; rollback must not depend on network).
5. **Eager boot load, refuse-not-degrade** — abort with the named scrubbed reason before the listener binds; tinybus never unloads, so the only good failure is at boot with a diagnosis.
6. **`opencompany modules check`** — no-load preflight: artifact, allowlist-present (absence FAILS: tinybus loads unverified without it), real-sha256 digest gate, tinybus's ancestor rule copied.
7. **Conformance** — `#[ignore]`d, `TINYMEMORY_TEST_MODULE`-gated, one-process-per-test (documented hang constraint): retains→assert_provider→facade round-trip through production `open_driver`, plus the module-vs-namespace **differential**.
8. **Migrate** — module accepted as a target; module→module refused by name (process singleton), never discovered as a hang.
9. **Docs** — mode-table row, ADR with the deliberately-not-doing list, failure-mode runbook incl. the restore-both-env-vars rollback rule.

## API Or Behavior Changes

None with the feature off — `tinymemory-module` is default-off, everything lives under `src/store/memory/module/` plus one arm in an existing match; a build without it is byte-identical except the always-compiled `modules` CLI enum (whose handler stub names the feature). `memory migrate` gains `--to module`.

## Tests

- [x] `cargo fmt --all -- --check` clean; `cargo clippy --features tinymemory-module --all-targets -- -D warnings` zero; `cargo clippy --locked --no-deps --features acp,runner,tinymemory --all-targets -- -D warnings` zero (all on the final tree)
- [x] Module lane `store::memory` 95/0; migrate suite 17/0; module+driver routing 24/0; embedded-lane regression 26/0; feature-lanes row + CI step included (the assert script requires them)
- [x] Both cfg directions compile (`--features tinymemory-module` and bare)
- [x] Full `openhuman,tinycortex` and bare suites passed on the pre-docs tree (4942/0, 3286/0); changed code since is cfg-gated out of both lanes — local rerun in progress after a disk-full interruption, CI authoritative

## Documentation

`docs/spec/runtime/memory-engine.md` mode table + `docs/spec/runtime/memory-module-port.md` (ADR + runbook). Gates Q1 (env injection — provisionally: the manager injects no `OPENCOMPANY_MEMORY`, so the canary must set both variables) and Q3 (pod securityContext) stay open on #1524 for PR 3.

## Summary by CodeRabbit

* **New Features**
  * Added a loadable TinyMemory module driver with isolated storage.
  * Added `modules check` to validate module configuration, integrity, and filesystem requirements.
  * Container builds now bundle and verify the TinyMemory module.
  * Startup eagerly loads the module and reports configuration errors if loading fails.
  * Added migration support for module-backed memory storage.

* **Bug Fixes**
  * Improved workflow validation error handling during creation.

* **Documentation**
  * Documented configuration, migration, recovery, isolation, rollout, and failure behavior.

* **Tests**
  * Added coverage for module loading, migration, preflight checks, and provider conformance.

### CODE REVIEW

**Comment by YellowSnnowmann** [comment]
Validation follow-up: the two full local lanes finished on the final tree after the disk-full interruption — `cargo test --features openhuman,tinycortex` **5005 passed / 0 failed**, bare `cargo test` **3344 passed / 0 failed**. Every stated local gate is now green on exactly what this PR ships (with the `zip 2.4.2` lock disambiguation in 63523f35).

File: Dockerfile [hunk 1]
```diff
@@ -55,7 +55,13 @@ RUN --mount=type=cache,target=/usr/local/cargo/registry \
...
 # `dist/pages-sdk/`, nested inside the same `dist/` the console itself builds
-# to, so the single `COPY --from=console /console/dist /app/console` below
+# to, so the single `COPY --from=console /console/dist /app/console
+# The TinyMemory module and its digest allowlist, side by side — tinybus reads
+# `modules.toml` from the library's own directory at attach time. root:root
+# 0755 the whole chain: tinybus refuses any group/other-writable ancestor, and
+# /app under the platform's securityContext satisfies its walk where /data
+# (fsGroup-mounted) never could.
+COPY --from=module /module /app/modules` below
 # already carries it into the runtime image with no second COPY needed.
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply Dockerfile]: Fixed in 707cdf35 — and worse than malformed: the automated edit had matched a COMMENT quoting the console COPY, so the console stage carried the broken instruction while the runtime stage never received the module at all. Comment restored, COPY now at the real site beside the console bundle.

File: src/store/memory/migrate.rs [hunk 2]
```diff
@@ -348,9 +349,46 @@ pub fn resolve_migrate_configs(
...
+                     (OPENCOMPANY_DATA_DIR also serves as its default when set)."
+                        .into(),
+                ));
+            }
+            MemoryDriverConfig {
+                mode: MemoryMode::Embedded,
+                driver_id: Some(to.to_string()),
+                url: None,
+                api_key: None,
+                data_dir,
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/migrate.rs:404]: Fixed in 707cdf35 — the module arm now carries the same mongodb ephemeral-scratch refusal as the namespace arm (durable --to-data-dir or the explicit OPENCOMPANY_MEMORY_ALLOW_EPHEMERAL=1 assertion).

File: src/store/memory/module/callbacks.rs [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+        } else if let Some(query) = word.find('?').filter(|_| word.contains("://")) {
+            out.push_str(&word[..query]);
+        } else {
+            out.push_str(word);
+        }
+        if out.len() >= SCRUB_MAX_BYTES {
+            break;
+        }
+    }
+    crate::store::text::slice_on_char_boundaries(&out, 0..SCRUB_MAX_BYTES)
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/callbacks.rs:84]: Fixed in 707cdf35 — the input is boundary-sliced to 4× the output cap before tokenising, so a whitespace-free flood costs O(cap) allocation, with room left for redaction markers.

File: src/store/memory/module/ops.rs [hunk 4]
```diff
@@ -0,0 +1,159 @@
...
+    // is load-bearing enough (risk #2 in the issue's register) that a future
+    // edit to the constant should trip a named refusal, not a data mix.
+    if dir.file_name().and_then(|name| name.to_str()) == Some("memory") {
+        return Err(
+            "the module store may not live in `memory` — that is the incumbent engine's \
+             directory, and interleaving the two schemas corrupts both"
+                .to_string(),
+        );
+    }
+    Ok(dir)
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/ops.rs:113]: Fixed in 707cdf35 — a data root that IS a `memory` directory is refused by name: `data_dir=/volume/memory` would nest the module workspace inside the incumbent engine's own tree.

File: src/store/memory/module/ops.rs [hunk 5]
```diff
@@ -0,0 +1,159 @@
...
+/// failure this process already cached. Every message is stable and names the
+/// variable, because the boot path prints it as the abort reason.
+pub async fn ensure_loaded(data_dir: &Path) -> Result<(), String> {
+    if let Some(cached) = LOADED.get() {
+        return cached.clone();
+    }
+
+    let outcome = load(data_dir).await;
+    LOADED.get_or_init(|| outcome).clone()
+}
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/ops.rs:167]: Fixed in 707cdf35 — the load is serialised through a tokio OnceCell's get_or_init future: exactly one caller runs admission, everyone else awaits and reads the one recorded outcome. The check-then-set race (and the loser's SETUP_FAILED poisoning the cache beside a loaded module) is gone.

File: src/store/memory/module/provider.rs [hunk 6]
```diff
@@ -0,0 +1,420 @@
...
+        // module that was never loaded has nothing to shut down.
+        if !host::is_started() {
+            return Ok(());
+        }
+        self.proxy("shutdown", false)
+            .await?
+            .call::<()>(methods::SHUTDOWN, ())
+            .await
+            .map_err(|error| from_bus(&error))
+    }
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/provider.rs:270]: Fixed in 707cdf35 — shutdown now honours its own comment: failures (including the started-runtime-but-failed-admission case, where proxy resolution re-surfaces the cached load error) are logged at debug and swallowed; the exit path always gets Ok.

**Comment by YellowSnnowmann** [comment]
@coderabbitai review

File: .github/workflows/ci.yml [hunk 7]
```diff
@@ -917,6 +947,52 @@ jobs:
...
+      # The bucket is ubuntu-24.04: this runner IS ubuntu-24.04 (glibc 2.39),
+      # which sits OUTSIDE the 22.04 archive's >=2.35 <2.39 window — the
+      # tenant image's bucket choice and this one differ for the same
+      # glibc-matching reason, each matched to where it runs.
+      - name: Fetch the pinned tinymemory module artifact
+        run: |
+          version="1.1.0"
+          archive="tinymemory-module-${version}-ubuntu-24.04-x86_64.tar.gz"
+          sha256="f5f10a71d1cdc58f91e6d1ac77c2b966dc9ede322a2ccf63048c1aeaf24e49a5"
+          curl -fsSL -o "$RUNNER_TEMP/$archive"             "https://github.com/tinyhumansai/tinymemory/releases/download/v${version}/${archive}"
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply .github/workflows/ci.yml:994]: Fixed in 297071bf — the job is now `runs-on: ubuntu-24.04`.

You are right that this was load-bearing rather than cosmetic. The archive this step downloads is the ubuntu-24.04 build precisely because its glibc window is bounded, and `ubuntu-latest` is a moving alias: the day GitHub advances it, the archive stops matching the runner and the module fails to `dlopen` at the first memory call. That surfaces as a broken memory test, not as an image bump, which is the worst possible place for it to appear. Same reasoning the Dockerfile already carries for choosing the 22.04 bucket for the bookworm-slim runtime — the two differ deliberately, each matched to where it runs, and this step was the one relying on a runner it did not pin.

File: .github/workflows/ci.yml [hunk 8]
```diff
@@ -917,6 +947,52 @@ jobs:
...
+          cargo test --locked --features tinymemory-module,tinymemory-embedded --lib --             --ignored --test-threads=1 the_module_driver_upholds_the_contract             | tee /tmp/module-e2e.log
+          grep -q "test result: ok. 1 passed" /tmp/module-e2e.log
+
+      - name: Module-vs-namespace differential against the real artifact
+        env:
+          TINYMEMORY_TEST_MODULE: ${{ runner.temp }}/tinymemory-module/libtinymemory_module.so
+          OPENCOMPANY_MEMORY_MODULE_PATH: ${{ runner.temp }}/tinymemory-module/libtinymemory_module.so
+        run: |
+          cargo test --locked --features tinymemory-module,tinymemory-embedded --lib --             --ignored --test-threads=1 the_module_and_namespace_drivers_agree             | tee /tmp/module-diff.log
+          grep -q "test result: ok. 1 passed" /tmp/module-diff.log
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply .github/workflows/ci.yml:1021]: Fixed in 297071bf — the step now asserts `libtinymemory_module.so` as well as `modules.toml`.

This one was worth more than a quick win, so recording why for the next reader. `test_artifact()` is

```rust
std::env::var("TINYMEMORY_TEST_MODULE").ok().map(PathBuf::from).filter(|p| p.is_file())
```

so it answers `None` when the path is not a real file, and both tests then return early. A skipped `#[ignore]`d test still prints `test result: ok. 1 passed`, which is precisely the string the `grep -q` guards below assert — so the lane could report green having never dlopened anything, and the guard I added to catch a vacuous run was itself vacuous. Checking only `modules.toml` left that open, because the archive could in principle extract its manifest and not its library.

Asserting the library makes the skip branch unreachable: the env vars point at exactly that path, and the path is now proven to exist before the tests run. The greps mean what they say again.

**Comment by YellowSnnowmann** [comment]
@coderabbitai review

The standing CHANGES_REQUESTED verdicts here are both stale — `64ef35d5` and `0f67b4b3`, while the head is `4beae41e`. Everything raised on them was fixed and answered in-thread:

- the artifact lane ran on `ubuntu-latest` while downloading a glibc-bounded ubuntu-24.04 archive — pinned to `ubuntu-24.04` (297071bf);
- the lane could report green without ever loading the module, because a skipped `#[ignore]`d test still prints `test result: ok. 1 passed`, which is exactly the string the guard grepped for — the step now asserts the shared library exists, making the skip branch unreachable (297071bf).

Two things landed since, from reviewing this PR end to end rather than waiting to be told:

- `export_page` now halves its page when the bus refuses it for size. A page crosses as ONE reply and replies cannot stream, so a 500-record default against document-sized chunks could exceed the 16 MiB frame and stop a migration on a byte count naming no knob (d2016096; upstream gap filed as tinybus#16).
- the runbook now says how the canary is actually run — the ms#49 ConfigMap channel, why the file form rather than the manager's own env, and the ordering that makes the result mean something (4beae41e).

CI is green on this head. Requesting a fresh verdict.

File: src/store/memory/module/provider.rs [hunk 9]
```diff
@@ -0,0 +1,527 @@
...
+///
+/// Matched on the message because tinybus reports it as a protocol error
+/// carrying the byte counts rather than a distinct variant — `encode` and
+/// `decode_length` both phrase it with the cap. Kept narrow on purpose: a
+/// broader match would silently halve pages for unrelated protocol faults,
+/// turning a real transport problem into a slow, quiet retry loop.
+fn is_frame_cap_refusal(error: &tinybus::Error) -> bool {
+    let message = error.to_string();
+    message.contains("-byte cap") || message.contains("over the")
+}
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/provider.rs:150]: Fixed in the push above — the predicate is now `error.to_string().contains("-byte cap")` alone.

You are right, and the evidence was already sitting in my own test. Both sites that raise the cap phrase it with the marker:

- `encode`: `"frame of {n} bytes exceeds the {MAX}-byte cap"`
- `decode_length`: `"peer announced a {n}-byte frame, over the {MAX}-byte cap"`

The test asserted both strings, and both contain `-byte cap` — so the `"over the"` alternative covered nothing the first marker missed, while widening the predicate across the arbitrary text `Error::Protocol` carries.

That matters more than a normal over-match because of what a false positive does here: it halves the export page and retries. An unrelated transport fault would not surface as a transport fault — it would become a quiet retry loop that ends by reporting "a single memory record does not fit the module bus frame", which is a wrong and confusing verdict about the operator's data.

Added the negative case you asked for: a protocol error that shares wording with the reader's phrasing (`"peer skipped over the handshake and sent a body"`) must not read as the cap. The test now pins the predicate in the direction it can actually regress.

**Comment by YellowSnnowmann** [comment]
## Merge-order note: #1550 and #1557 do not compile together

Verified by merging all five open OpenCompany branches into `main` in a scratch worktree. Git reports **zero textual conflicts** and produces a tree that does not build:

```
error[E0063]: missing field `deployment` in initializer of `MemoryDriverConfig`
   --> src/store/memory/migrate.rs:399
   --> src/store/memory/upstream_conformance_test.rs:271
```

#1550 adds two `MemoryDriverConfig` literals (the `module` migrate target and the `module_config` test helper); #1557 adds a `deployment` field to that struct. Each PR is green on its own, and neither diff touches the other's lines, so nothing surfaces until they are both in.

Adding the field to those two literals is the whole fix. With it, the merged tree compiles and the full suite passes — **3623 passed, 0 failed** — so this is the only conflict between the five, and it is mechanical rather than behavioural.

Deliberately not "fixing" this by giving `MemoryDriverConfig` a `Default` and using `..Default::default()`: `MemoryMode` has no defensible default, and this module's own docs rule one out — *"Never selected as a fallback when a configured driver fails to bind — a company that believes it is remembering and is not is the failure this whole surface exists to prevent."* The exhaustive literal is the type system doing its job; the gap is that no lane builds the union.

CI checks out `refs/pull/N/merge` (no `ref:` override), so whichever of the two merges second will fail its own CI once the first lands, and the fix is obvious from the error. The only way this reaches `main` is merging on a **stale green tick** — a tick from before the other PR landed. Re-run CI on the second PR after the first merges, rather than trusting the existing one.

**Comment by YellowSnnowmann** [comment]
Two gaps found reviewing this driver against how it will actually be run, both fixed in 299a0aa4.

## A frame-cap refusal was unactionable

`from_bus` funnelled it into `MemoryError::Other`, so the operator saw a raw protocol string.

That matters more than it looks, because `export_page` is the only member that can *answer* a refusal — it has a page size to halve, which this PR already does. Every other member returns its whole answer in one reply, and a reply cannot stream. `list` has no page size to shrink and returns a whole namespace, and the facade reads are built on it:

```
FactStore::list      -> bound.list(company)
ContextStore::list   -> bound.list(company)
recent_traces        -> bound.list(company)
```

So a namespace that outgrows the 16 MiB cap stops being readable **through this driver** while staying readable through `namespace` and every hosted engine. That is a real ceiling rather than a tuning problem, and the difference between an operator moving the tenant and an operator staring at `protocol: frame of N bytes exceeds the 16777216-byte cap` is entirely in the message. It now names the cap and both remedies.

A test pins it, and pins the negative half too — an unrelated protocol fault must not be dressed up as a frame-cap refusal, or the advice becomes noise. Mutation-tested rather than assumed: disabling the branch fails the test with the raw string.

## The runbook did not name the two quietest failures

It said to watch for quiet outcomes, which is right, but both of the quietest ones leave a **healthy pod**:

- **The store is empty by construction.** The module writes under `memory-module/`, `namespace` under `memory-namespace/` — separate on purpose, since sharing would interleave two schemas. A flipped tenant therefore starts with no memory, every read succeeds returning nothing, and that is indistinguishable from a working driver with nothing stored yet.
- **A failed module does not fail the boot.** Loading is lazy and `modules check` is a manual command, so a bad artifact boots fine and errors on every memory call — permanently, since the bus never unloads a library.

The runbook now says the success criterion is a **write followed by a read** through the flipped tenant, on a tenant chosen for having little memory to begin with so "empty" stops being ambiguous.

## Validation

`cargo test --features sqlite,mongodb,tinymemory-module --lib` — 3517 passed, 0 failed. `cargo fmt --all -- --check` clean.

Separately: this branch and #1557 do not compile together. Details in the earlier comment on this PR.

**Comment by YellowSnnowmann** [comment]
Closed the merge-order break rather than leaving it documented, since a comment describing a break is weaker than CI proving its absence.

`#1557` is merged into this branch and the two literals now carry the `deployment` field:

```
src/store/memory/migrate.rs            (the `module` migrate target)
src/store/memory/upstream_conformance_test.rs   (the `module_config` helper)
```

Exactly the two sites the scratch merge predicted — nothing else surfaced behind them. Over the composition: **3583 passed, 0 failed**, `cargo fmt --all -- --check` clean, `cargo clippy --all-targets -- -D warnings` clean.

This branch is the one that should carry the dependency: #1557 is approved and green, this one is still in review, so the order that costs least is #1557 first. **The extra files in this diff are #1557's and disappear when it lands** — after that this branch is its own changes plus the two-line fix.

Worth being explicit about why the fix is these two lines rather than something structural. Giving `MemoryDriverConfig` a `Default` and using `..Default::default()` would prevent the whole class, but it needs a default `MemoryMode`, and this module's docs rule one out — *"Never selected as a fallback when a configured driver fails to bind — a company that believes it is remembering and is not is the failure this whole surface exists to prevent."* The exhaustive literal is the type system doing its job. What was missing was a lane that built the union, which is what this merge supplies.

File: Dockerfile [hunk 10]
```diff
@@ -77,6 +77,34 @@ ENV OPENCOMPANY_BIND=0.0.0.0:8080 \
...
+RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \
+    && rm -rf /var/lib/apt/lists/*
+RUN set -eu; \
+    archive="tinymemory-module-${TINYMEMORY_MODULE_VERSION}-${TINYMEMORY_MODULE_PLATFORM}.tar.gz"; \
+    curl -fsSL -o "/tmp/${archive}" \
+      "https://github.com/tinyhumansai/tinymemory/releases/download/v${TINYMEMORY_MODULE_VERSION}/${archive}"; \
+    echo "${TINYMEMORY_MODULE_SHA256}  /tmp/${archive}" | sha256sum -c -; \
+    mkdir -p /module; \
+    tar -xzf "/tmp/${archive}" -C /module; \
+    test -f /module/modules.toml
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply Dockerfile]: Fixed in 6e7b3903. Right, and the distinction is the useful part: the digest proves the archive is the one that was pinned, and says nothing about what is inside it. An archive carrying the manifest but not the library builds a green image that cannot start — and it fails at boot rather than at first use, because `serve` loads the module eagerly. Both files are checked now, with a comment recording why the digest is not sufficient on its own.

File: docs/spec/runtime/memory-module-port.md [hunk 11]
```diff
@@ -0,0 +1,176 @@
...
+  `memory-namespace/` — deliberately separate, because sharing a directory
+  would interleave two schemas silently. So a flipped tenant starts with no
+  memory whatever it had before, and every read succeeds while returning
+  nothing. That is indistinguishable from a working driver with nothing
+  stored yet, which is exactly why the probe has to write first.
+* **A failed module does not fail the boot.** Loading is lazy — the first
+  `proxy()` call resolves it — and `modules check` is an operator command
+  nothing runs automatically. A bad artifact therefore boots a healthy pod
+  whose every memory call errors, and TinyBus never unloads a library, so it
+  stays that way until the process restarts.
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply docs/spec/runtime/memory-module-port.md]: Fixed in 6e7b3903 — the doc was mine and it was wrong.

I wrote that loading is lazy, having found `ensure_loaded` called from `proxy()`. It is called there, but `serve` also calls it during startup and propagates the failure (`src/bin/opencompany.rs`), so a bad artifact refuses to boot rather than serving a pod whose every memory call errors.

That is the better outcome, and the runbook was describing the worse one — which would have had an operator watching for a symptom that cannot occur while missing that the pod never came up. The neighbouring sentence counted two quiet failures; only the empty-store one is quiet, so it now says so.

File: src/store/memory/facades.rs [hunk 12]
```diff
@@ -293,13 +293,31 @@ impl Bound {
...
             .iter()
-            .filter_map(|entry| decode(entry, &namespace))
+            .filter_map(|entry| {
+                let decoded = decode(entry, &namespace);
+                if decoded.is_none() {
+                    eprintln!(
+                        "PR1550DEBUG list decode_failed key={} content={:?}",
+                        entry.key, entry.content
+                    );
+                }
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/facades.rs]: Fixed in 63b3605c — all seven removed.

Worth recording that I first checked my local branch, found nothing, and was about to answer that these did not exist. They did: the debugging commits had been pushed to this branch and my checkout predated them. The PR's HEAD stopped being my HEAD, and I verified against the wrong tree.

On the finding itself: `entry.content` on both decode-failure paths, the caller's `query` on recall, and company ids, addresses and labels on `delete_label`. `ContextStore::list` is reachable from `GET /memory`, so these run in production. Removed rather than downgraded to gated `tracing`, because the useful half — that a decode failed and for which key — is already recorded by the `corrupt` warning without the body.

File: src/store/memory/module/ops.rs [hunk 13]
```diff
@@ -0,0 +1,221 @@
...
+/// is not resolvable here.
+fn normalized_lexically(path: &Path) -> PathBuf {
+    use std::path::Component;
+    let mut out = PathBuf::new();
+    for component in path.components() {
+        match component {
+            Component::CurDir => {}
+            Component::ParentDir => {
+                out.pop();
+            }
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/memory/module/ops.rs]: Fixed in 63b3605c, with a regression test.

`out.pop()` answers `false` on an empty buffer and changes nothing, so a leading `..` was dropped and `../data` resolved to `data` — a sibling of the intended directory rather than its parent, chosen silently because both are valid paths. The doc comment directly above already promised the opposite, so the code contradicted its own stated contract.

It now keeps `..` where there is nothing to pop, composes `../..` rather than collapsing it to `..`, and still treats `..` at an absolute root as the no-op the doc describes. The test covers all four shapes. The pre-existing gate tests still pass, which is the half worth checking — a fix that let the module store nest inside the incumbent engine's directory would have traded a quiet misdirection for data corruption.

**Comment by YellowSnnowmann** [comment]
@codex review

CodeRabbit is rate-limited on this SHA, so requesting a second pass here instead.

The last three pushes carry: the four review fixes (Dockerfile `.so` check, the lazy-load doc correction, removal of seven debug statements that logged stored memory, and the dropped-`..` path fix), plus the module conformance failure.

That last one is worth a look specifically. `fa1678a6` sets `embeddings_provider: "none"` in the module config: the engine's embedder factory opts out of vector search on that value alone, while `embedding_dimensions: 0` only describes the width the host embeds into. Without it the module went looking for a real embedder, embedded into a zero-width vector, and matched nothing — silently, since an empty result set is also what "nothing matched" looks like. The in-process `namespace` driver never hit it because it is handed a `NoopEmbedding` object directly and the factory is never consulted.

**Comment by YellowSnnowmann** [comment]
## #1568 removed the ground under this branch — it needs a decision, not a conflict resolution

`main` now conflicts with this PR in eight files, and resolving them would be the wrong move: #1568 deleted what several of them exist to use.

```
namespace_provider / NAMESPACE_DRIVER_ID   gone from main
tinymemory-embedded feature                gone from main
tinycortex feature + tinymemory-core dep   gone from main
Rust (openhuman, tinycortex) CI lane       gone from main
```

Merging over that would re-add code #1568 deliberately removed, through the back door of a conflict resolution that looks clean. So the merge is aborted and the branch is where it was.

Three things this branch loses outright:

- **The differential test.** `the_module_and_namespace_drivers_agree` compared the module against the same engine in-process. There is no in-process driver now, so the comparison has nowhere to stand — and it was the test that caught the recall divergence fixed in `fa1678a6`.
- **The gated lane.** `Rust (openhuman, tinycortex)` is where the module conformance step ran against the real artifact. It no longer exists, so that step needs a new home or it silently runs nowhere.
- **`tinymemory-embedded`.** Several tests here are gated on it.

## What #1568 did and did not change for the compile-time goal

It removed OpenCompany's **direct** engine dependency. It did not remove the engine from the tenant image, because the runtime still pulls it:

```
$ cargo tree --features mongodb,openhuman,tinymemory -i tinycortex
tinycortex
└── openhuman
    └── opencompany

$ cargo tree ... -i tinymemory-core
tinymemory-core
└── openhuman
    └── opencompany
```

`TENANT_FEATURES` still contains `openhuman`, and `vendor/openhuman/Cargo.toml` still declares `tinycortex`, `tinymemory`, `tinymemory-api`, `tinymemory-core` and `tinymemory-tinycortex` **non-optionally**. So the image that ships still compiles the whole stack, and the loadable-module driver still cannot avoid it there. That remains openhuman#5560's to fix, unchanged by #1568.

## The question worth answering before more work goes in

#1568's summary says the intent is to "retain only base-store, hosted-provider, and null memory modes". This PR adds a fourth — an in-pod engine reached over the bus rather than linked. That is a different thing from the embedded backend #1568 removed, and it is the only in-pod option that does not link the engine, but whether it is still wanted is a product call that #1568 appears to have answered implicitly.

Reworking this branch onto the new shape is doable — drop the differential and the `tinymemory-embedded` tests, find a lane for the module conformance step — but it is real work, and it is wasted if the answer is "hosted only from here".

Happy to do either. Flagging rather than guessing, because the cost of guessing wrong is a rework that resurrects a dependency somebody just spent a PR removing.

**Comment by YellowSnnowmann** [comment]
Closing — superseded by #1568.

The mode this driver hangs off no longer exists. `MemoryMode` on `main` is now `Remote` and `Null`; `Embedded` is gone, along with `namespace_provider`, the `tinycortex` and `tinymemory-embedded` features, and the `Rust (openhuman, tinycortex)` lane this PR's conformance step ran in. Reworking onto that shape would mean re-adding a memory mode that was deliberately removed, so this is a close rather than a rebase.

Recording what the branch produced, because most of it has already landed elsewhere and the rest is worth not rediscovering.

**Merged independently:** #1557 (label-scoped delete across six backends, the live-engine lane, and the `U+FFFD` envelope escape that stopped real silent data loss against Supermemory), #1560, and tinymemory#81 (Supermemory strips `U+FFFD` and `U+0000` from stored content — found by that live lane).

**Defects found on this branch and fixed here**, which die with it but are worth knowing about if any of this code is ever revived:

- Seven `PR1550DEBUG` statements logged `entry.content`, the caller's `query`, and company ids from `ContextStore::list` — reachable from `GET /memory`. Never on `main`; confirmed.
- `normalized_lexically` dropped a leading `..`, so `../data` resolved to `data`. The doc comment directly above already promised otherwise.
- A frame-cap refusal landed in `MemoryError::Other`, telling an operator nothing about a namespace that had outgrown the 16 MiB bus reply.
- The image build verified the archive digest but not that the archive contained the library.

**Filed upstream:** tinymemory#84 — a module configured with `embedding_dimensions: 0` and no `embeddings_provider` reaches a state that cannot work and cannot say so. The engine's factory opts out of vector search on `embeddings_provider == "none"` and on nothing else, so the module embedded queries into zero-width vectors and matched nothing, silently. Found only because the conformance step ran the same engine in-process and over the bus and compared them — five feature sets and every in-process double passed straight through it.

**Measured, and still relevant to openhuman#5560:** the bus proxy is 16.2% faster on a clean release build of a slim feature set (208s vs 248s), and buys nothing on the tenant image, because `vendor/openhuman` declares the TinyMemory/TinyCortex stack non-optionally:

```
tinycortex      ← openhuman ← opencompany
tinymemory-core ← openhuman ← opencompany
```

#1568 removed OpenCompany's own dependency; the engine still arrives through the runtime. That makes openhuman#5560 the remaining lever on compile time, not an optional cleanup.
