### ISSUE TITLE
main does not compile its gated test targets: #1134 and #1182 collided semantically

### ISSUE THREAD

**Issue by M3gA-Mind** [tinyhumansai/opencompany#1197]
## Summary

`upstream/main` does not compile its **gated test targets**. Two PRs that were each green on their own lane merged 1h20m apart and left main red — a semantic merge conflict, invisible to both.

Reproduced on a clean checkout of `main` (`8d58d442`), with no local changes:

```
$ cargo check --locked --features openhuman,tinycortex --tests
error[E0560]: struct `ports::types::CycleRequest` has no field named `compressed_history`
   --> src/harness/spend_halt_turn_test.rs:379:9
error[E0560]: struct `ports::types::CycleRequest` has no field named `roster`
   --> src/harness/spend_halt_turn_test.rs:380:9
error[E0560]: struct `ports::types::CycleRequest` has no field named `context_index`
   --> src/harness/spend_halt_turn_test.rs:381:9
error: could not compile `opencompany` (lib test) due to 3 previous errors
```

## The two halves

| | |
| --- | --- |
| **#1134** (`harness: say when a turn was stopped for spend`) | merged 19:32:37Z. Added `src/harness/spend_halt_turn_test.rs`, whose `CycleRequest` literal sets the three fields. |
| **#1182** (`chore/dead-memory-path`, commit `c778c33e` "drop the CycleRequest fields no brain reads") | merged after. Removed those three fields. |

Neither is wrong. #1182's own lane was green against a main that did not yet contain the new test file, and #1134's was green against a `CycleRequest` that still had the fields. The merge is textually clean and semantically broken — nothing in either PR's lane could have caught it.

## Why it needs fixing now rather than at leisure

`cargo check --tests` is what the gated `Rust (openhuman, tinycortex)` lane compiles, so **every open PR's gated lane now fails for a reason that has nothing to do with its diff.** With several PRs in flight that is a lot of wasted investigation, and the real risk is the one this shape always carries: a genuine breakage arriving while the lane is already red gets read as "the known main breakage" and merged past.

`--lib` alone stays green, which is exactly why this survived: a lib-only check is blind to a struct-field change that only test fixtures depend on.

## The fix

Three lines. `src/harness/spend_halt_turn_test.rs:379-381` is the **only** remaining consumer in the tree —

```
$ grep -rn "compressed_history" src/
src/harness/spend_halt_turn_test.rs:379:        compressed_history: Vec::new(),
src/ports/types.rs:2001:/// ... the struct once also carried `compressed_history` ...
```

— the second hit being #1182's own doc note recording the removal, which is correct and stays. So: delete the three field initialisers from that literal. No behaviour change; the test asserts nothing about them.

I introduced the file in #1134 and have the fix built and verified locally (`--features openhuman,tinycortex --tests` clean with it, reproduced red without it). Happy to raise it immediately.

## Worth a guard, separately

This is the second time a clean merge has left main not compiling. A cheap `cargo check --locked --features openhuman,tinycortex --tests` on **push to main** would catch the class at merge time rather than on the next PR to notice — filing that thought here rather than as its own issue until someone wants it.
