### PR TITLE
fix(tasks): a card records the thread it was raised in, not just the channel (#1890 B)

### PR DESCRIPTION
**Pull request by sanil-23**
## Summary

Sub-issue **B** of #1890 — *a card remembers its thread*.

A `TaskRecord` has recorded `origin_chat_id` since #151 and a settle has carried it
onto `DeskTaskCompleted` since #377, but both name the **channel**. A channel holds
any number of live threads, so a card raised inside one settled its marker flat in
the channel and **the thread that asked for the work never showed it finishing**.
`chat_seed` says so in its own words on `main`:

> a card records `origin_chat_id` and no thread root, so there is currently no
> honest answer to which thread it belongs to

This supplies the answer. `TaskRecord` gains `origin_parent: Option<EventSeq>`,
additive on exactly the terms `origin_chat_id` and `parent_task_id` took; the three
card-raising paths stamp it; the terminal captures it off the card at the single
settle emission point; and both the history projection and the SSE frame carry it
to the console, where the renderer already threads by `parentId` and needed no
change at all.

The plumbing A left behind is what makes this small: `DelegationRunner` was already
bound to the raising turn's root by #1896's `in_thread` builder, so B is that root
reaching the board.

**Blocks nothing, unblocks C.** `in_thread` now admits a terminal on the same
parent-pointer rule a message takes, so C ("settle markers reach the model") becomes
a change to the seed's *mapper* alone rather than to the filter as well. B is
behaviour-neutral for the seed today — a settle is still not a turn — and there is a
test pinning exactly that.

### Where it lands

| | |
|---|---|
| `ports/tasks.rs` | `TaskRecord::origin_parent` |
| `ports/types.rs` | `DeskTaskCompleted::origin_parent` |
| `runtime/delegation.rs` | the hand-off card and the `spawn_task` drain stamp `self.thread_root` |
| `server/operator.rs` | the REST chat handler stamps the root off the **journaled** message |
| `harness/built_in/brain.rs` | the settle captures it; the publish chain carries a `ChatTarget` |
| `server/chat_history.rs` | the marker projects with `parent_id` |
| `server/operator.rs` | the `desk_task_completed` frame carries `parentId` |
| `harness/built_in/chat_seed.rs` | `in_thread` answers for a terminal |
| `frontend/src/lib/chat.ts` | `dispatchMarkerPlacement` prefixes it into the console's id namespace |

### Three decisions worth reviewing

**The REST handler reads the root off the journaled event, not off the request
body.** `AcceptedTurn::thread_root()` — the body names a parent by id as a *string*,
and the append has already parsed and validated it. Two readings of one thread root
is how the board and the transcript drift, which is #435's failure mode one layer
up. It is the same reason `run_chat` takes an `AcceptedTurn` rather than a loose
parent.

**The publish chain takes a `ChatTarget` instead of a bare channel.** The
channel/root pair travels four frames down `file_conversation_batch` →
`file_publishes_on_card` → `record_conversation_publishes`, and two bare `Option`s
beside each other is precisely the mis-pairing hazard `ChatTarget`'s own docs name.
This also **fixes a pre-existing half-read**: the approval-grant path passed
`grant.origin_thread` alone to `record_conversation_publishes` while the delegation
drain three lines below it was already bound to `grant.origin_parent` — a grant has
carried both halves since A.

**`origin_parent` on the SSE frame is stringified and omitted-not-null.** Same shape
`chatId` takes, and the same rendering `chat/history` gives a message's parent — the
live marker and its rehydrated twin have to agree, or a marker would render inline
live and jump into a thread on reload, which is the split the `h<seq>` identity
dedupe exists to close. There is a test asserting the two produce the same value.

## API Or Behavior Changes

- **Additive only.** Both new fields are `#[serde(default, skip_serializing_if)]`, so
  no stored board migrates on any backend and an unthreaded settle is byte-identical
  on the wire to a pre-B one. A pre-B journal line replays as channel-level.
- **`desk_task_completed` gains an optional `parentId`**, alongside the existing
  optional `chatId`. Absent means channel level.
- **A card raised inside a thread now settles into that thread**, so its marker
  leaves the channel timeline and appears in the thread panel, counting toward the
  root's "N replies" chip. `distinctSenders` already skips `system`, so the reply
  facepile is unchanged. A card raised at channel level is untouched — that is the
  overwhelmingly common case.
- **One known gap, deliberate and commented at the site.** `POST …/tasks` ("Add to
  board") writes `origin_parent: None` because the create body carries a channel and
  no thread — exactly what that route did before B, so nothing regresses. Closing it
  needs a body field plus a console change (the transcript holds a rendered message
  id, not an `EventSeq`), which belongs with the renderer work in the epic's **D**.

## Tests

Every test below was confirmed to fail with the corresponding line reverted, except
where noted.

- `a_card_raised_inside_a_thread_records_its_root`, `a_spawned_card_records_the_thread_that_queued_it` — the two delegation card sites
- `a_chat_card_remembers_the_thread_inside_the_channel` — the REST handler, end to end through the route
- `a_settled_card_journals_the_thread_it_was_raised_in` / `..._channel_level_card_journals_no_thread` — the card → terminal capture, read back off a real journal
- `a_terminal_raised_in_a_thread_projects_into_that_thread` — the history projection, plus that `owns` still routes it to its channel
- `desk_task_completed_projects_the_thread_...` / `..._omits_the_parent_for_a_channel_level_card` — the SSE frame, present and absent
- `the_terminal_carries_the_thread_its_card_was_raised_in` — serde round trip, skip-when-absent, and a pre-B line replaying
- `a_settle_belongs_to_the_thread_that_raised_its_card` and three siblings — `in_thread`. The two *negative* cases (a sibling's thread, the channel-level conversation) pass on `main` too, since the old code rejected every terminal outright; they guard against a too-lax rule rather than proving the fix.
- `a_terminal_inside_this_thread_is_still_not_seeded_as_a_turn` — B changes no seed
- `into the thread inside that channel, under the host's own id namespace` / `flat in the channel...` (vitest) — the console placement, and that it matches what `fromHistory` mints
- The store conformance `populated` fixture now seeds a real root, so a backend silently dropping the field fails on every store.

Run locally:

- [x] `cargo fmt --all -- --check`
- [x] `cargo clippy --locked --all-targets -- -D warnings`
- [x] `cargo clippy --locked --no-deps --features openhuman --all-targets -- -D warnings`
- [x] `cargo clippy --locked --no-deps --features acp,runner,tinymemory --all-targets -- -D warnings`
- [x] `cargo test --locked`
- [x] `cargo test --locked --features openhuman --tests`
- [x] `pnpm typecheck`, `pnpm typecheck:unit`, `pnpm typecheck:e2e`, `pnpm vitest run` (3869 passed)

## Documentation

The field docs are the documentation — both new fields carry the `None`-is-the-channel
rule, the read-as-a-pair rule, and the additive-wire note. #1890's own **Status**
section will be updated when this merges.

Part of #1890. Deliberately no closing keyword: the epic holds nine items and one
would retire it.

## Summary by CodeRabbit

* **New Features**
  * Task cards created from threaded conversations now retain their originating thread.
  * Completed task markers and live updates appear in the correct thread.
  * The operator channel is now available as a durable workflow destination.

* **Bug Fixes**
  * Fixed mismatches between live task markers and reloaded conversation history.
  * Improved filtering for threaded task completions.
  * Notifications now respect the currently open channel and thread.
  * Added safeguards against conflicting reserved channel identifiers.

### CODE REVIEW

File: frontend/src/lib/chat.ts [hunk 1]
```diff
@@ -390,6 +401,7 @@ export function dispatchMarkerPlacement(
     message: makeMessage("system", dispatchMarkerText(event.column), {
       taskId: event.taskId,
       messageId: String(event.seq),
+      parentId: event.parentId ? hostMessageId(event.parentId) : undefined,
```
[the remark this answers is not in the document]
Comment (sanil-23) [reply frontend/src/lib/chat.ts:404]: Confirmed and fixed in 971ab78ec — this was a real regression I introduced.

`isViewingTaskOrigin` deferred to the inline marker on a channel match, which was sound while every marker rendered inline. A parented marker is folded into its root's replies by `buildTimeline`, so with the thread panel closed (or open on a sibling) there was no toast and nothing on screen — the same defect #1768's review established the rule against, one layer away from it.

The shell now tracks the open thread root (`openThreadRootRef`, fed from `onChannelViewed`, whose ChatView effect already lists `openThreadId`) and requires it to match before trusting the channel. An unparented marker still renders inline, so the channel check alone stays correct for it — `root == null ||` is what keeps that case working. Pinned in `chat-task-origin-visibility.test.ts`, alongside #1768's own cases.

File: src/server/operator.rs [hunk 2]
```diff
@@ -1142,6 +1143,20 @@ fn project_event_for_viewer(
...
+            // conversation, which is where every marker landed before.
+            //
+            // The live frame and `chat/history`'s rehydrated twin must agree on
+            // this or the marker would render inline live and jump into a
+            // thread on reload — the split the `h<seq>` identity dedupe exists
+            // to prevent. Stringified for the same reason the history
+            // projection's `parentId` is: the console keys threads by message
+            // id, and a message id is a string there.
+            if let Some(parent) = origin_parent {
+                o["parentId"] = json!(parent.value().to_string());
```
[the remark this answers is not in the document]
Comment (sanil-23) [reply src/server/operator.rs:1418]: Fair, and done in 971ab78ec. `docs/spec/runtime/events.md` now has a "The thread inside that channel" subsection under the #377 settle-marker section, covering: `origin_parent` on both `TaskRecord` and `DeskTaskCompleted`, captured-never-derived on the same terms as its channel half; the read-as-a-pair rule (a bare `None` means "channel level" only when a channel is named, and nothing at all when it is not); both wire surfaces, including that the frame carries a **string** and omits it rather than sending null; the additive serde contract and pre-B replay; and the one creation path (`POST …/tasks`) that still writes `None`. The event index entry links to it too.

**Comment by sanil-23** [comment]
Rebased onto current \`main\` — and carrying a fix for it.

\`main\` at 7474e3ca2 **does not compile**: \`CompanyRecord\` gained a required \`created_at_millis\` and two \`.save(&CompanyRecord { … })\` literals in \`builder.rs\`'s tests do not set it. Verified on a clean checkout of main with no branch of mine involved:

```
error[E0063]: missing field `created_at_millis` in initializer of `CompanyRecord`
    --> src/runtime/builder.rs:5086:20
    --> src/runtime/builder.rs:8804:20
```

A semantic merge conflict rather than a bad edit: the PR that added the field updated the literals it could see, and a PR merged alongside it carried these two. Both were green on their own merge refs; only the combination is red — which is the one state no PR's CI builds. That is why this PR's first run was fully green and its second was not.

Fixed in 5abf4df57 as its own commit, `None` matching the six sibling literals that already set it, so it is easy to drop if a maintainer would rather land it separately.

Local gates on the merged tree, all green: `cargo test --locked`, `cargo test --locked --features openhuman --tests`, clippy on default and `openhuman`, `cargo fmt --all --check`, plus `pnpm typecheck` and 3941 vitest tests.
