### PR TITLE
ContextStore: label-scoped delete, one claim per (addr, label)

### LINKED ISSUE #1300: ContextStore: multi-label-per-address semantics diverge across backends, and shared addresses are a forget-griefing vector
Spun out of the #1290 review (its shared-address minor). Two related defects in how content-addressed context chunks handle byte-identical bodies under different labels:

**1. Backend divergence on the second label.** fs appends an index entry per `put` — one address can carry N labels. sqlite (`INSERT OR IGNORE`) and mongodb (`$setOnInsert`) and the provider facade are first-write-wins on `(company, addr)` — the second `put` of identical content under a different label returns a success receipt (the addr) for a row that never landed under that label. A caller listing by their label finds nothing on those backends, everything on fs. The conformance suite uses distinct bodies everywhere, so nothing pins either behavior.

**2. Shared addresses make memories permanently un-forgettable (fs).** `memory_forget` and the fact-mirror reap both refuse address-level deletion when any other label shares the address — correct fail-safe, but on fs any agent can make another agent's memory (or an operator-fact mirror) permanently un-deletable from those surfaces by storing byte-identical text. No escape hatch exists below the operator console.

Options to evaluate: label-scoped delete on the port (removes one index entry; blob refcounted — fs is close already, sqlite/mongo need a labels column/array); salting the address with the label (kills dedup, breaks existing addrs — probably no); or documenting first-write-wins as the contract and making fs conform (loses fs's multi-label listing, changes existing data). Whichever way, the conformance suite needs identical-body-two-label cases so the chosen semantics are pinned on every backend.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Addendum (from the #1290 CodeRabbit round):** both shared-address guards (`memory_forget`, `reap_fact_mirror`) check a snapshot and then delete — a byte-identical write landing in between loses its row (TOCTOU). The label-scoped delete option closes this by construction (deleting one label entry cannot orphan another's); any other chosen semantics needs a conditional delete on the port. The interleaving regression tests belong with whichever lands.

### PR DESCRIPTION
**Pull request by YellowSnnowmann**
Closes #1300.

## What this changes

`ContextStore` gains **`delete_label(company, addr, label)`** beside the existing address-level `delete`, and every backend now keeps **one claim per `(addr, label)`** — the semantics the fs index always had, and the ones sqlite/mongodb/the provider facade silently did not.

Of the three options the issue put up, this is the first (label-scoped delete). Salting the address would kill dedup and move every existing addr; documenting first-write-wins would have made fs lose its multi-label listing and thrown away data on migration. Label-scoping is also the only one the addendum's TOCTOU falls out of for free.

## The two defects

**1. Backend divergence on the second label.** A byte-identical body stored under a second label returned a success receipt (the addr) for a row that never landed on sqlite (`INSERT OR IGNORE`), mongodb (`$setOnInsert`) and the provider facade — a caller listing by their own label found nothing there and everything on fs. Now every backend lands the claim:

| backend | how a claim is stored |
|---|---|
| fs | one index row per `(addr, label)` — `put` still appends O(1), the set semantics are applied on read (see below) |
| sqlite | new `context_chunk_labels (company_id, addr, label, stored_ms)` table; body row unchanged, `list` joins |
| mongodb | `$addToSet` into a `labels` array on the one document; the scalar `label` stays the first claim |
| provider facade / tinycortex engine | `labels` vec on the stored envelope, `#[serde(default)]` |
| tinycortex in-memory | one `StoredChunk` row per claim |

**2. Shared addresses made memories permanently un-forgettable.** `memory_forget` and `reap_fact_mirror` refused to delete any address another label shared — so any agent could make another agent's memory (or an operator-fact mirror) undeletable forever by storing byte-identical text. Both now remove **their own claim**; the body is reaped only with its last claim, decided atomically inside the backend (fs: under the index lock; sqlite: one transaction; mongo: a conditional delete that cannot match a document a concurrent `$addToSet` just touched; facade/engine: a per-store lock).

That atomicity is what closes the addendum's **TOCTOU**: the old guards read a snapshot and then deleted, so an identical-content write landing in the window lost its row. `assert_delete_label_survives_a_concurrent_identical_put` drives delete and put concurrently for 32 rounds on every backend and demands the writer's claim and body survive each one.

`memory_ingest`'s `forget_document` had the same snapshot guard and gets the same treatment — it previously *skipped* shared chunks, leaving a forgotten document's claims listed forever.

## Compatibility

- **`delete` is unchanged** and still address-level: the operator hard-delete takes the body and every claim.
- **sqlite** heals at open, in one transaction: backfills a claim for any body row that lacks one (a pre-#1300 database, or a row an older binary wrote since) and sweeps claims whose body row an older binary's address-level delete removed. Idempotent, and a label-scoped delete can never be undone by it.
- **mongodb / the facade / the engine** union the legacy scalar `label` with the new set on every read, and keep the scalar pointing at a live claim — so a rollback to a pre-#1300 binary still reads what it always read. Tests seed the legacy shape directly rather than assuming.
- No new cargo feature, no migration to run, no config.

## Why `put` still appends on fs

Checking `(addr, label)` membership at write time would read and parse the whole index on every write — and the ingest path writes one chunk per document fragment, so a single folder drop becomes a quadratic scan. `put` stays an O(1) append and `list` collapses duplicates (first row wins, so the stamp matches the other backends' first-write-wins); `search` dedupes by address, which also fixes fs reporting one hit per claim where every other backend reports one per body. `a_duplicate_index_row_reads_back_as_one_claim_and_deletes_whole` pins both halves together, including that `delete_label` takes every duplicate row (a survivor would resurrect a forgotten claim).

## Conformance

The suite used distinct bodies everywhere, which is why nothing pinned either behaviour. Three new shared asserts, run on **fs, sqlite, mongodb, the provider facade, the real namespace driver, the tinycortex in-memory client and the tinycortex engine**:

- `assert_identical_body_two_labels` — one address, both claims listed, each findable by its own prefix, and a re-`put` of an identical `(body, label)` adds nothing.
- `assert_delete_label_scoped` — one claim goes, the body survives while another claims it, the body is reaped with the last claim, absent/repeat claims answer `false`, and address-level `delete` still takes everything.
- `assert_delete_label_survives_a_concurrent_identical_put` — the interleaving regression above.

Plus per-backend mixed-version tests (sqlite heal, mongo legacy scalar document, engine legacy record) and the Brain-view row-id case.

## Console

A context row's id was `ctx:{addr}`, whose own comment promised unique React keys — two labels on one address collided. It is now `ctx:{addr}:{label}`, and the newest-first cap tie-breaks on `(addr, label)` so the order stays total. The console treats the id as opaque (no parsing), so nothing else moves.

## Commands run

```
cargo fmt --all -- --check
cargo clippy --locked --all-targets --features mongodb,sqlite,tinymemory,tinymemory-embedded -- -D warnings
cargo clippy --locked --all-targets --features openhuman,tinycortex -- -D warnings
cargo test --locked --features mongodb,sqlite,tinymemory,tinymemory-embedded --lib store::
cargo test --locked --lib server::ops::memory
cargo test --locked --features openhuman,tinycortex --lib -- store::tinycortex memory_tools server::ops::memory memory_ingest
```

The mongodb backend's tests skip themselves without `OPENCOMPANY_TEST_MONGODB_URI`, so they were also run locally against a real `mongod` — 48 passed, including the three new conformance asserts and `legacy_scalar_label_documents_list_and_label_delete`. In CI the `Rust (mongodb)` job runs them against its `mongo:7` service.

## Summary by CodeRabbit

* **New Features**
  * Shared memory content can now be associated with multiple labels.
  * Deleting a memory removes only the selected label, preserving shared content used elsewhere.
  * Shared content is automatically cleaned up after its final label is removed.
  * Memory listings and search results now handle shared content consistently.

* **Bug Fixes**
  * Prevented shared memories from being incorrectly skipped or deleted entirely.
  * Improved duplicate-write handling and preserved backward compatibility across storage backends.

* **Tests**
  * Added coverage for multi-label storage, scoped deletion, concurrency, migrations, and legacy records.

### CODE REVIEW

**Comment by YellowSnnowmann** [comment]
@coderabbitai review

File: src/store/conformance.rs [hunk 1]
```diff
@@ -2475,6 +2477,291 @@ pub async fn assert_multibyte_bodies_survive_search_and_ranged_peek(
...
+                        ContextChunk {
+                            label: "race/second".to_string(),
+                            body,
+                        },
+                    )
+                    .await
+            })
+        };
+        deleter.await.unwrap().unwrap();
+        writer.await.unwrap().unwrap();
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/conformance.rs:2751]: Fixed in 33b3a78d.

The premise is right: `tokio::spawn` does not place the `put` between the last-claim read and the reap, so this test cannot, on its own, fail a stale-snapshot implementation. I have made the comment say exactly that rather than imply otherwise.

I have not added a failpoint, because the finding pointed at a better fix — removing the window instead of instrumenting it:

- **fs, sqlite, the provider facade, the tinycortex engine and its in-memory client hold a lock (or a transaction on the single connection) across the whole `delete_label`**, and `put` takes the same one. There is no read-then-write window to hit on any of them, whatever the scheduler does, so a failpoint would have nothing to pause between — the property is structural, and this test is the regression lock that fails if someone removes that serialisation.
- **mongodb was the one backend with a real window** — it genuinely was two round-trips. Your sibling comment on `put` is a consequence of exactly that window. It is now one atomic operation per outcome: a conditional `delete_one` carrying `{"$expr": {"$setEquals": [<claim union>, [label]]}}` when this is the last claim, or a single pipeline `update_one` when others remain. The condition is evaluated server-side as part of the write, so a concurrent put either lands before it (and the delete matches nothing) or after it (and re-creates the document through its upsert). There is no longer a moment between a read and a delete for a `put` to be forced into.

Where the state a forced interleaving would have produced is still reachable — by a rollback, or a build that predates this — I test it deterministically rather than by racing: `a_put_restores_a_missing_scalar_label_and_keeps_first_write_wins` seeds that document shape directly and asserts the next write heals it.

Kept this test for what it is worth: it exercises both calls concurrently on every backend for 32 rounds with fresh content each round, which is a real regression lock on the serialisation, and on mongodb it does drive genuinely concurrent server-side writes.

File: src/store/mongodb.rs [hunk 2]
```diff
@@ -998,6 +1037,80 @@ impl ContextStore for MongoStore {
...
+            chunks
+                .delete_one(doc! {
+                    "company_id": id.as_ref(),
+                    "addr": addr.as_ref(),
+                    "label": {"$exists": false},
+                    "$or": [{"labels": {"$exists": false}}, {"labels": {"$size": 0}}],
+                })
+                .await
+                .map_err(mongo_err)?;
+        }
```
[the remark this answers is not in the document]
Comment (YellowSnnowmann) [reply src/store/mongodb.rs]: Fixed in 33b3a78d.

Valid, and thank you — this was a real bug in the invariant the PR claims.

Confirmed the path: `delete_label` removed the last claim and then reaped in a second round-trip, so a `put` matching the document in between skipped `$setOnInsert` entirely and `$addToSet` left `labels: ["B"]` with no scalar `label`. The claim itself was safe (the conditional reap correctly stopped matching), but the document was then permanently unreadable to a pre-#1300 `list`, which does `get_str("label")?`.

Fixed on both sides:

1. **`put` is now an update pipeline** instead of `$setOnInsert` + `$addToSet`. `$ifNull` expresses first-write-wins per field *and* restores a scalar it finds missing:
   ```
   label: {$ifNull: ["$label", <this write's label>]},
   body:  {$ifNull: ["$body",  <body>]},  …
   labels: <existing ∪ this label, deduped in order>
   ```
   On an upsert insert every field is missing and takes this write's value, so the previous semantics are unchanged; on an existing document each keeps what it has.

2. **The window itself is gone.** `delete_label` is no longer update-then-reap. It is one atomic operation per outcome:
   - last claim → a single `delete_one` whose filter carries `{"$expr": {"$setEquals": [<claim union>, [label]]}}`, evaluated server-side as part of the delete, so a concurrent put that adds a second claim first simply makes it match nothing;
   - claims remain → a single pipeline `update_one` that removes the claim and re-points the scalar at a survivor in the same write.

   Neither branch can leave a document without a scalar, so there is no intermediate state for a concurrent reader or writer to observe.

Added `a_put_restores_a_missing_scalar_label_and_keeps_first_write_wins`, which seeds the scalar-less shape directly (a rollback or an older build could still leave one) and asserts the next `put` heals it while `stored_ms` stays at the first write.

Verified against a live `mongod`, not just the doubles.

**Comment by YellowSnnowmann** [comment]
Two commits added after the approval, so flagging that the scope grew — this is a data-correctness fix, not cleanup.

The live lane this PR adds found real corruption, not just the vendor defect already recorded here. Supermemory strips `U+FFFD` as well as `U+0000`, and only the second of those was insulated by the JSON envelope:

| character | in the envelope | reaches the engine | before this fix |
|---|---|---|---|
| `U+0000` | escaped by RFC 8259 | no | survived |
| `U+FFFD` | emitted literally | yes | **silently dropped** |

Measured through the real facade path against the live service, not modelled:

```
sent="before<U+0000>after"  got="before<U+0000>after"  survived
sent="before<U+FFFD>after"  got="beforeafter"          LOST
```

So any record whose text contained `U+FFFD` was reading back one character shorter than it was written, with no error and a decode that succeeded against the wrong string. `U+FFFD` is the one that matters in practice — it arrives in any text that has been through a lossy decode.

`encode` now escapes it. The escaped and literal forms are the same string to every JSON reader, so decoding is unchanged and records already written the other way keep working. The live host-ports test passes with it and failed without.

Worth calling out that the module doc here previously reasoned "the envelope insulates this host" — correct for the character that had been measured, wrong for the one that had only been argued about, and wrong in the direction that loses data quietly. That doc is corrected in the second commit, because the reasoning is what let this through rather than the code.

The `the_live_supermemory_service_upholds_the_provider_contract` test stays red against a real key until the vendored pin moves: that is the engine-side half, fixed upstream in tinymemory#81. The host-ports half — the one that decides whether a tenant can run on this engine — is green.

Validation: `cargo clippy --locked --all-targets -- -D warnings` and the `openhuman,tinycortex` lane both clean, `cargo test --features tinymemory --lib` 3482 passed, `cargo test --locked` 3374 passed, plus the live run above.

**Comment by YellowSnnowmann** [comment]
Your live credentials for Mem0 and Cognee turned up a defect that no double could have caught, so this PR grew again.

## Two of three engines could not be bound at all

Every remote engine here was constructed with `::new(url, key)` — which is each adapter's **self-hosted** constructor. Mem0 and Cognee each ship two products speaking different protocols under one driver id:

| engine | managed platform | self-hosted | what OpenCompany sent | result |
|---|---|---|---|---|
| Mem0 | `Authorization: Token`, v3/v1 paths | `X-API-Key`, un-prefixed | self-hosted | **HTTP 404** |
| Cognee | `X-Api-Key` | bearer token | self-hosted | **HTTP 401** `{"detail":"Invalid header"}` |
| Supermemory | bearer | bearer (same API) | either — identical | passed |

Supermemory is why this went unnoticed: it serves one API to both deployments on one credential, so the single constructor worked against the one engine we had a key for. The other two were unusable, and the failure named neither the cause nor the fix.

## The change

An explicit `OPENCOMPANY_MEMORY_DEPLOYMENT` (`managed`, the default, or `self-hosted`) selects the constructor. Explicit rather than inferred: Cognee Cloud is a per-tenant hostname, so there is nothing in the URL to key on, and a wrong guess fails at the first request.

Managed is the default because that is what `remote` mode is for, and because nothing is being changed under anyone — the manager injects no `OPENCOMPANY_MEMORY` today, so no tenant runs this.

The enum lives in `store::select` rather than `store::memory`, which is gated behind `tinymemory`; `StorageSettings` is not, and referencing a gated module from it broke the `openhuman,tinycortex` lane.

## Live results, all three services

| engine | provider contract | **host ports** |
|---|---|---|
| Supermemory | fails — NUL mangling (tinymemory#80, fixed in tinymemory#81, red until the pin moves) | **pass** |
| Mem0 | **pass** | **pass** |
| Cognee | fails — HTTP 500 storing a 64 KB record | **pass** |

**All three now pass the host port suite** — the claim that decides whether a tenant can run on an engine. Both contract failures are engine-side deviations on raw content, not defects here, and the split between the two suites is what makes that legible: Cognee is usable by OpenCompany while failing the raw-content contract.

Cognee's 500 is worth knowing before rollout: its own `api/v1/update` returns `Internal server error` for a 64 KB record, having treated the whole envelope as an `Input word`. Happy to file it upstream the way tinymemory#80 was.

## Test changes

The offline doubles speak the self-hosted dialect, so their config now says so — pointing the managed client at them would 404 and read as a broken adapter rather than a mismatched double. The managed path production defaults to is covered offline by a new test asserting each vendor's credential header per deployment, mutation-tested by swapping in the other deployment's header.

Also fixed a defect of my own from the last push: the awkward-content facts persisted in live accounts, so `listed.len() == 1` failed on the *second* run of a suite that passed on the first. They now use their own company and are deleted after; I purged the stale records from all three accounts.

## Validation

`cargo test --features tinymemory --lib` 3483 passed, `cargo test --locked` 3374 passed, `cargo fmt --all -- --check` clean, `cargo clippy --locked --all-targets -- -D warnings` and the `openhuman,tinycortex` lane both clean, plus the live run above.

**Comment by YellowSnnowmann** [comment]
## Merge-order note: #1550 and #1557 do not compile together

Verified by merging all five open OpenCompany branches into `main` in a scratch worktree. Git reports **zero textual conflicts** and produces a tree that does not build:

```
error[E0063]: missing field `deployment` in initializer of `MemoryDriverConfig`
   --> src/store/memory/migrate.rs:399
   --> src/store/memory/upstream_conformance_test.rs:271
```

#1550 adds two `MemoryDriverConfig` literals (the `module` migrate target and the `module_config` test helper); #1557 adds a `deployment` field to that struct. Each PR is green on its own, and neither diff touches the other's lines, so nothing surfaces until they are both in.

Adding the field to those two literals is the whole fix. With it, the merged tree compiles and the full suite passes — **3623 passed, 0 failed** — so this is the only conflict between the five, and it is mechanical rather than behavioural.

Deliberately not "fixing" this by giving `MemoryDriverConfig` a `Default` and using `..Default::default()`: `MemoryMode` has no defensible default, and this module's own docs rule one out — *"Never selected as a fallback when a configured driver fails to bind — a company that believes it is remembering and is not is the failure this whole surface exists to prevent."* The exhaustive literal is the type system doing its job; the gap is that no lane builds the union.

CI checks out `refs/pull/N/merge` (no `ref:` override), so whichever of the two merges second will fail its own CI once the first lands, and the fix is obvious from the error. The only way this reaches `main` is merging on a **stale green tick** — a tick from before the other PR landed. Re-run CI on the second PR after the first merges, rather than trusting the existing one.
