### PR TITLE
fix(workflows): bound what a fan-in hands an agent turn (#849)

### LINKED ISSUE #849: workflows: nothing bounds what a fan-in hands an agent, so a 3-source gather intermittently dies on CONTEXT_LENGTH_EXCEEDED after the fetches are paid for
## What happens

A workflow fans out three `web_fetch` nodes and feeds all three payloads into one agent node. The agent turn intermittently dies on a raw provider 400:

```
This run failed at "rank": harness error: capability error: harness agent 'analytics_analyst':
harness error: turn for 'analytics_analyst': tinyagents harness run failed: model error:
model error: inference returned 400 Bad Request:
{"success":false,"error":"The conversation is too long for model 'chat-v1'. Please start a new chat.",
 "errorCode":"CONTEXT_LENGTH_EXCEEDED"}
```

## It is intermittent, which is what makes it bad

Across 26 runs of the same unmodified workflow, seven reached the `rank` node:

| Time | rank | Outcome |
|---|---|---|
| 19:50:01 | 14.0s | ok |
| 19:51:13 | 44.5s | ok |
| 19:51:47 | 16.3s | ok |
| 19:50:38 | 17.3s | ok |
| 19:58:49 | 17.0s | **CONTEXT_LENGTH_EXCEEDED** |
| 19:59:07 | 22.9s | **CONTEXT_LENGTH_EXCEEDED** |
| 20:03:55 | 23.2s | **CONTEXT_LENGTH_EXCEEDED** |

**4 succeeded, 3 failed — same graph, same nodes, same sources.** The variable is how much text the three sport sections happened to return that minute (observed range for a single fetch: 8.9k–14.7k characters). The workflow is therefore a coin flip that gets worse as the pages get busier, and an operator has no way to know which they will get.

## The gap

Nothing bounds what a node hands to an agent. Three fetched pages are concatenated into the turn verbatim — no truncation, no summarise-then-rank, no per-node payload cap, and no check against the target model's context before the call. The failure is discovered by the provider, after the tokens for the fetches are already spent, and surfaces to the operator as a raw upstream 400 with a vendor string (*"Please start a new chat"*) that means nothing in a workflow context.

Fan-in is a normal shape — gather N sources, rank them — so this is not an exotic graph.

## Expected, roughly in order of value

1. **Bound the payload** a `tool_call` node contributes to a downstream agent turn (cap + truncate with a marker, or summarise per source before fan-in).
2. **Fail before spending.** The context budget for the configured model is knowable at fan-in; check it and report *which* inputs overflowed rather than passing an oversized turn to the provider.
3. **Translate the error.** "The conversation is too long for model 'chat-v1'. Please start a new chat" is unactionable inside a workflow — the operator cannot start a chat. Say which node, which inputs, and what to do.

## Environment

Staging, `marketing--agentic-marketing-agency`, tier **Full**, workflow `daily-sports-news-blog`, model `chat-v1`, 13 Aug 2026.

### PR DESCRIPTION
**Pull request by M3gA-Mind**
## Summary

Closes #849.

A workflow's `agent` node folded **every** predecessor's output into its turn verbatim. Nothing bounded that channel, so a three-source gather intermittently died on a raw provider 400 — after the fetches were already paid for:

```
inference returned 400 Bad Request: {"success":false,
 "error":"The conversation is too long for model 'chat-v1'. Please start a new chat.",
 "errorCode":"CONTEXT_LENGTH_EXCEEDED"}
```

Four of seven runs of the *same* graph over the *same* sources succeeded. The only variable was how much text the pages happened to return that minute. A workflow whose outcome is a coin flip is the defect, not the 400.

New module `src/workflows/caps/upstream.rs`, wired into the existing #782 fold in `caps/mod.rs`:

1. **The payload is bounded.** At most `DEFAULT_UPSTREAM_BUDGET_CHARS` (32,000) characters per turn — **the whole rendered section, truncation markers and separators included, not merely the source text inside them** (see the review round below) — divided **max-min fairly** across the predecessors — a short source is served in full and the large ones split what is left. A 300-character wire item beside two 200k pages keeps all 300. A flat per-source cap does not fix starvation, and a running total makes the result depend on which branch finished first.
2. **Truncation is visible to both the model and the operator.** Each cut source carries a `[TRUNCATED BY OPENCOMPANY — source 2 of 3 produced 14700 characters; the 10000 above are all that was kept and the remaining 4700 were NOT read. Do not describe this source as if you have seen all of it.]` marker **in the turn itself**, so the agent knows it is holding a fragment and cannot present it as the whole; *and* the run carries an operator notice on `WorkflowRun::notices` — the #638 channel added for exactly this shape of fact — naming how much arrived, how much fitted, how many sources were cut, and the remedy. Silent truncation would be worse than the 400 it prevents.
3. **The provider refusal is translated.** A context-window 400 is rewritten before it reaches the run: it names what is actually too big (the number of feeding steps, the step's own instruction, the teammate's accumulated session history), what to do about each, and keeps the provider's own words at the end for support.

## API Or Behavior Changes

**Behaviour, agent nodes only.** An `agent` node's turn now carries at most 32,000 characters of upstream text. Every run below that budget — the overwhelming majority — composes a **byte-identical** message to before, raises no notice and is unaffected; pinned by `an_ordinary_fan_in_is_untouched_and_says_nothing` and the pre-existing `no_upstream_output_is_byte_identical`.

A run whose input exceeds the budget now **succeeds with truncated input plus a notice**, where it previously either succeeded or failed on a provider 400 depending on page size.

Error text for a context-window refusal changes shape (the vendor sentence is replaced, the vendor string retained). Every other error passes through unchanged, pinned by `unrelated_errors_are_not_relabelled`.

No public API change. `DEFAULT_UPSTREAM_BUDGET_CHARS` is `pub(crate)` and `#[cfg(test)]`-re-exported for one assertion.

### Review round: the bound did not cover its own reporting

CodeRabbit flagged (Major) that the first cut of this change bounded source text and then appended an **unbudgeted** marker per truncated source and an unbudgeted separator between each pair, with no final limit. It holds, and rather than reason about it I measured it:

| | |
| --- | --- |
| Marker | **209 characters**, one per truncated source |
| Separator | 7 characters, one per pair |
| 1,000 oversized sources under a 32,000-character budget | **243,886 characters rendered — 7.6× the budget** |

That is issue #849's own failure reappearing through #849's fix. The three-source tests never saw it because the assertion slack (`MARKER_SLACK: 2000`) covered about **eight** markers — worth stating plainly, because the missing coverage was a *class* of test, not a single case: nothing asserted on the **final rendered section**, only on per-source slices and whole-message size at small N.

**A second instance the review did not mention, found while fixing it:** the separators are unbudgeted *even when nothing is truncated*. Ten thousand one-character sources all fit the text budget and still added 70,000 characters of separator. Same root cause, same fix — credit for the marker case is CodeRabbit's, the separator case is mine.

**The invariant is now: the rendered section never exceeds `budget`, markers and separators included.** One number, one assertion, one function's postcondition. Paid for three ways, each where it fits — this is deliberately *both* of the options the review offered plus a third, because they solve different halves:

- **Reserved** — each truncation marker is charged to the allowance of the source it describes. That is the honest place for it: the marker exists because that source was cut and stands in the space the cut text vacated.
- **Aggregated** — predecessors there is no room for at all collapse into one `[OMITTED BY OPENCOMPANY — 469 of this step's 500 inputs …]` line. This is the half that must not scale with source count, and it does not.
- **Capped, by derivation not by magic number** — `max_rendered_sources(budget) = budget / MIN_SOURCE_SHARE_CHARS` (1,024), so 31 at the default budget. **This is what makes per-source markers affordable at all**; reservation alone does not bound a thousand markers, it merely makes each cost a source its text. A thousand 32-character shards is noise with the shape of data — no model can rank them — so the honest rendering is 31 readable sources plus a line saying 469 were not shown.

Per-source markers survive for the sources that *are* rendered because aggregating them away would buy budget by deleting the signal: the marker sits at the exact point the text stops, which is what stops a model narrating a source it has only seen the opening of. One aggregate line cannot do that job. The reasoning is in the module doc, not only here.

An unconditional `clamp_to_budget` backstops the arithmetic, and `the_backstop_is_never_what_enforces_the_budget` asserts it does **not** fire on any known path — a clamp that bites routinely hides a mis-accounting rather than guarding against one.

`MAX_MARKER_CHARS` (320) is now pinned by test at both markers' numeric extremes (`usize::MAX` in every field), so a future edit that makes a marker wordier fails a test instead of silently spending budget it was not reserved. The module doc carries a standing table of everything emitted, its count and its size, since breaching that property is how this broke.

The operator notice now distinguishes truncated from omitted — *"31 of them were truncated and a further 469 could not be shown to it at all"* — because a fragment and an absence are different facts about what the step saw.

**Not fixed, flagged:** `RunNotices` itself is uncapped. That is pre-existing and shared with the #638 approval and board-write producers; this change adds one notice per agent node turn, the same rate they push at, so it introduces no new scaling factor. Capping it would change that contract and belongs in its own change.

### Three judgement calls a reviewer should weigh

**1. Truncate-and-report rather than fail-the-run — this contradicts the issue text, deliberately.**

The issue (which I wrote) asks to *fail before spending*. That framing is wrong, and reading only the issue will make this look like a missed requirement. By the time a fan-in is composed the spending has **already happened** — the fetches ran first. Failing there throws that paid work away and delivers the operator nothing, in order to avoid a turn that a bounded input makes succeed. So the boundary is enforced by *bounding*, before the request is composed, and the "which inputs overflowed" report rides the marker and the notice instead of an error. The one overflow that can still reach the provider — a turn whose own instruction, tool schemas or session history is what is too large — is what the error translation exists for.

**2. An advertised context window may LOWER the budget and never raise it.**

`chat-v1`'s nominal window is enormous and the turn was refused a long way inside it, because the advertised figure describes the model rather than the turn and says nothing about the system prompt, the tool schemas or the session history sharing it. Trusting it upward is exactly how a fan-in gets handed more than the provider will take; trusting it downward is safe and worth doing, so a small model gets a proportionally smaller budget. The reasoning is in the code at `budget_chars`, not only here.

**3. I did NOT thread a node id into `translate`, and the issue's "name the node" is met another way.**

`AgentRunner::run_agent` receives the resolved node *config* — `prompt`, `input`, `agent_ref` — never the node id, so naming the node in the error would mean adding a `node_id` key in `translate` and carrying it through config resolution. I did not, because the console **already** names it: `RunHistoryPanel` renders `This run failed at "rank": ` from the #371 node trail, so the operator reads the node name immediately before this message. The error names the agent ref, the inputs and the remedy; the node name is supplied by the surface it appears on. Say the word if you would rather have it in the string too.

For the same reason the marker says `source 2 of 3` rather than naming the producing node: the `input = "=items"` binding resolves to the item set with no provenance, and changing that binding is precisely the shape #782 pinned. Carrying provenance through the fold is a follow-on, not a drive-by.

### The bound is at the join, not at the producer

Worth stating because it is the natural review question. A cap on a `tool_call` node's own output would bound each fetch separately and still let three bounded fetches sum to an oversized turn, and it would have to spend its cap blind to how many siblings were about to arrive. It would also miss every other producer — an upstream `agent` node's reply is unbounded in exactly the same way, and a `transform` can manufacture a large payload from a small one. **A single enormous `web_fetch` into one agent runs the same unbounded path as the three-way fan-in** (`a_single_enormous_source_is_bounded_too`), and one rule at the join covers both.

This is a different resource from `ports::bound_node_output`, which clips the persisted run-output snapshot after a run settles against a durable-storage ceiling. A node's output can be well inside that cap and still be more than a turn will take. Noted in the module doc so the two are not confused.

## Tests

27 new tests. 19 pure unit tests in `upstream.rs`, 7 fold-level tests in `caps/mod.rs`, and 1 end-to-end test through the real graph → `translate` → `run_workflow` → `HarnessAgentRunner` → `HarnessPool` with only the model stubbed.

**Every payload is synthetic.** The reported failure is intermittent *because* it depended on what a live sports section returned that minute, so a test that fetched a real page would be the same coin flip.

### Revert-and-check, round two (the marker budgeting)

I neutralised each of the four new mechanisms independently — cap → `usize::MAX`, up-front charge → removed, marker reservation → removed, clamp → pass-through. **All 5 new tests failed**, none vacuous:

```
a_thousand_oversized_sources_stay_inside_the_budget .............. FAILED  243886 chars for a 32000 budget
a_thousand_way_fan_in_cannot_smuggle_its_markers_past_the_budget . FAILED  245941-character turn
the_bound_holds_at_every_scale_and_budget ........................ FAILED  133 chars under a 0 budget
sources_past_the_useful_limit_are_aggregated_into_one_line ....... FAILED
a_truncation_marker_is_paid_for_by_its_own_source ................ FAILED
```

`the_bound_holds_at_every_scale_and_budget` sweeps 6 source counts × 7 budgets including 0 and the 1,023/1,024 boundary either side of the derived cap.

### Revert-and-check, round one (the original bound)

I neutralised each behaviour in place — budget → `usize::MAX`, allocation → keep everything, marker → empty string, notice → `None`, translation → `None` — and re-ran. **13 of the 19 failed.** The end-to-end test failed with the bug in its message:

```
the fan-in turn must not carry both payloads whole: 136965 characters for a 32000-character budget
```

**The other 6 still passed with the fix reverted, by design, and are not claimed as coverage of it:** `sources_that_fit_are_untouched`, `an_untruncated_fold_raises_no_notice`, `an_ordinary_fan_in_is_untouched_and_says_nothing`, `unrelated_errors_are_not_relabelled`, `truncation_respects_character_boundaries`, and the `budget_chars(None)` arm. They are no-regression and no-overreach guards — the under-budget path must stay byte-identical, and the error translator must never relabel an unrelated failure — and a no-op trivially satisfies them. They prove the change breaks nothing, not that it does anything.

### Commands run locally

- [x] `cargo fmt --all -- --check` — clean
- [x] `cargo clippy --no-deps --features openhuman,tinycortex --all-targets -- -D warnings` — clean. Ran with `--no-deps` to mirror CI; a bare `--all-targets` fails on vendored-crate lints CI never evaluates.
- [x] `cargo build --all-targets` — clean (default features). Also `cargo check --features openhuman,tinycortex --lib`, since default features compile none of `src/workflows`.
- [x] `cargo test` — 2340 passed, 0 failed (default features). Also `cargo test --features openhuman,tinycortex --lib` — **3619 passed, 0 failed**, which is the run that actually exercises this change.

### A pre-existing local failure, flagged not fixed

`workflows::agent_upstream_input_test` stack-overflows at the default thread stack size. **This reproduces on unmodified `upstream/main`** — I checked out pristine `src/workflows/` and confirmed it before writing anything. CI sets `RUST_MIN_STACK: 16777216` on the gated lane; all 306 `workflows::` tests pass at that exact value locally. Not caused by this PR, and out of scope for it, but it will bite anyone running these tests locally without the env var.

### One unverified observation from the issue data

In the issue's table the four passes are all 19:50–19:51 and the three failures all 19:58–20:03 — **monotone in time**. The harness keeps one live session per roster agent and history survives across turns, so `analytics_analyst`'s accumulated session history is a plausible second variable alongside page size. I did not confirm this: isolating it needs many staging runs and no single run distinguishes the two causes. It is a hypothesis, not a finding — it is why the error translation names session history as a suspect, and why bounding the fold reduces the growth rate as well as the peak.

## Documentation

`docs/spec/runtime/workflow-vocabulary.md` gains a section on what an `agent` node receives from upstream and its bound: the budget, the fair division, why the bound is at the join rather than the producer, that truncation is never silent, and that a bounded turn is not a failed run. Module-level rationale lives in `src/workflows/caps/upstream.rs`.

## Summary by CodeRabbit

* **New Features**
  * Workflow agents now receive bounded upstream inputs with fair allocation across sources.
  * Oversized content is truncated with visible markers while preserving contributions from each predecessor.
  * Operators receive run notices when upstream content is truncated or sources are omitted.
  * Provider context-window errors now include workflow-specific guidance.

* **Documentation**
  * Added documentation describing upstream input handling, budgeting, truncation, and error guidance.

### CODE REVIEW

**Comment by M3gA-Mind** [comment]
@coderabbitai review

**Comment by M3gA-Mind** [comment]
@coderabbitai review

**Comment by M3gA-Mind** [comment]
@coderabbitai review

File: src/workflows/caps/mod.rs [hunk 1]
```diff
@@ -955,16 +1016,59 @@ fn append_upstream_input(instruction: &str, request: &Value) -> String {
...
+            continue;
+        }
+        // Cut, and say so in the turn itself: an agent that cannot tell it is
+        // holding a fragment will present the fragment as the whole source.
+        let mut section = upstream::truncate_chars(text, kept);
+        section.push_str(&upstream::truncation_marker(index + 1, of, produced, kept));
+        sections.push(section);
+    }
+    Some((
+        sections.join("\n\n---\n\n"),
```
[the remark this answers is not in the document]
Comment (M3gA-Mind) [reply src/workflows/caps/mod.rs]: Verified against the current code, and it holds. Fixed in 46196cf4.

**I measured it rather than trusting the estimate.** A marker is **209 characters**, a separator 7. Under a 32,000-character budget, 1,000 oversized sources rendered **243,886 characters — 7.6× over**. That figure now sits in the PR body, because "roughly 1,000 marker strings" reads like a hypothetical and 243,886 does not.

Why the three-source tests never caught it, stated plainly since the gap was a *class* of test rather than a single case: the assertion slack (`MARKER_SLACK: 2000`) covered about **eight** markers, and nothing asserted on the **final rendered section** at all — only on per-source slices and on whole-message size at small N. That is the assertion this adds.

**One instance you did not flag, found while fixing yours:** the separators are unbudgeted *even when nothing is truncated*. Ten thousand one-character sources all fit the text budget and still added 70,000 characters of separator. Same root cause, so the same fix covers it — noting it separately so the record is clear about which half came from where.

## What changed

The invariant is now **the rendered section never exceeds `budget`, markers and separators included** — one function's postcondition (`bound_sections`) rather than a property spread across a loop and a module. Both of your suggestions are in, plus a third, because they solve different halves:

- **Reserved** — each truncation marker is charged to the allowance of *the source it describes*. The honest place for it: the marker exists because that source was cut, and stands in the space the cut text vacated.
- **Aggregated** — predecessors there is no room for at all collapse into one `[OMITTED BY OPENCOMPANY — 469 of this step's 500 inputs …]` line. This is the half that must not scale with source count.
- **Capped, by derivation** — `max_rendered_sources(budget) = budget / MIN_SOURCE_SHARE_CHARS` (1,024) → 31 at the default budget. **This is what makes per-source markers affordable at all.** Reservation alone does not bound a thousand markers; it only makes each cost a source its text. A thousand 32-character shards is noise with the shape of data — nothing can rank them — so the honest rendering is 31 readable sources plus a line naming the 469 that were not shown.

Per-source markers survive for the sources that *are* rendered, deliberately: the marker sits at the exact point the text stops, which is what stops a model narrating a source it has only seen the opening of. Aggregating it away would buy budget by deleting the signal, and one aggregate line cannot do that job. The reasoning is in the module doc, not just here.

An unconditional `clamp_to_budget` backstops the arithmetic, and `the_backstop_is_never_what_enforces_the_budget` asserts it does **not** fire on any known path — a clamp that bites routinely hides a mis-accounting rather than guarding one.

`MAX_MARKER_CHARS` (320) is pinned by test at both markers' numeric extremes (`usize::MAX` in every field), so a wordier marker in a future edit fails a test instead of silently spending budget it was not reserved. The module doc now carries a standing table of everything emitted, its count and its size, since breaching that property is how this broke.

## The many-source test you asked for

Two, asserting the **final rendered section**:

- `a_thousand_oversized_sources_stay_inside_the_budget` — pure, 1,000 sources.
- `a_thousand_way_fan_in_cannot_smuggle_its_markers_past_the_budget` — fold level, through the real envelope shape a graph produces.
- plus `the_bound_holds_at_every_scale_and_budget`, sweeping 6 source counts × 7 budgets including 0 and the 1,023/1,024 boundary either side of the derived cap.

**Proven non-vacuous.** With the four new mechanisms neutralised independently, all 5 new tests fail:

```
a_thousand_oversized_sources_stay_inside_the_budget .............. FAILED  243886 chars for a 32000 budget
a_thousand_way_fan_in_cannot_smuggle_its_markers_past_the_budget . FAILED  245941-character turn
the_bound_holds_at_every_scale_and_budget ........................ FAILED  133 chars under a 0 budget
sources_past_the_useful_limit_are_aggregated_into_one_line ....... FAILED
a_truncation_marker_is_paid_for_by_its_own_source ................ FAILED
```

`cargo test --features openhuman,tinycortex --lib` → **3,619 passed, 0 failed**. fmt and `clippy --no-deps -D warnings` clean.

**One thing not fixed, flagged instead:** `RunNotices` is itself uncapped. That is pre-existing and shared with the #638 approval and board-write producers; this change pushes one notice per agent node turn, the same rate they already do, so it adds no new scaling factor. Capping it changes that contract and belongs in its own change.

**Comment by M3gA-Mind** [comment]
@coderabbitai review

**Review by oxoxDev — APPROVED** [review]
The framing is the right one and it is worth stating as plainly as you did:

> Four of seven runs of the *same* graph over the *same* sources succeeded. The only variable was how much text the pages happened to return that minute. **A workflow whose outcome is a coin flip is the defect, not the 400.**

And the cost detail is what makes it urgent rather than annoying: the run dies *after* the fetches are paid for, so every failed coin flip is spend with nothing to show.

**"Truncation is never silent, and never unbudgeted"** is the property I came looking for, and both halves are there:

- the agent gets a `[TRUNCATED BY OPENCOMPANY — source i of n …]` marker **in the turn**, so it knows it is holding a fragment rather than reasoning confidently over a truncated page — the difference between a bounded input and a quietly wrong one;
- the operator gets a `WorkflowRun::notices` line naming how much arrived and how much did not, so the bound is visible outside the model's context too.

Counting the **marker and separator** against the budget rather than only the source text inside them is the detail I would have missed on a first pass, and finding it because your own first cut emitted 243,886 characters is the right way to have found it. A bound that does not budget for its own announcement is not a bound.

Aggregating sources below `MIN_SOURCE_SHARE_CHARS` into one `[OMITTED BY …]` line, rather than handing the model a dozen unreadable slivers, is the correct shape too — a fragment too small to be usable is worse than an honest omission, because it looks like evidence.

**0 major. 1 note. Approving.**

### Note — `notices` now has a second producer

This writes to `WorkflowRun::notices`, which #714 introduced for the approval-overflow line. I asked there whether that collection wants a bound, given it is journaled onto `WorkflowRunFinished` and grows with the workflow — and noted it was the one unbounded collection in a change whose subject was what happens when a bound is exceeded.

That question is now slightly more live, for a nice reason: a second producer means the field is the general channel rather than one feature's, and a graph with many fanned-in agent nodes can emit a truncation notice per node. Nothing here is wrong — this is exactly what that channel is for — but whoever answers #714's question should know it is answering it for two callers now, not one.

**Before merging:** the branch is `MERGEABLE`; lanes still reporting. #714 touches the same field and is still open, so worth confirming they compose once both are in.

File: src/workflows/caps/upstream.rs [hunk 2]
```diff
@@ -0,0 +1,887 @@
...
+            (0, omitted) => format!("{omitted} of them could not be shown to it at all"),
+            (cut, 0) => {
+                let verb = if cut == 1 { "was" } else { "were" };
+                format!("{cut} of them {verb} truncated")
+            }
+            (cut, omitted) => format!(
+                "{cut} of them were truncated and a further {omitted} could not be shown to it at \
+                 all"
+            ),
+        };
```
[the remark this answers is not in the document]
Comment (oxoxDev) [reply src/workflows/caps/upstream.rs:467]: Verified against the current code, and it holds. Fixed in f6f0d1c0.

The reachability is worth stating precisely, because it changes what the fix is for. The only caller — `render_upstream_input` — drops blank items before it composes, so today no omitted row can have `produced == 0` and the miscount cannot be reached from production. What the subtraction was, then, is a postcondition of `bound_sections` (the omitted rows are the trailing ones, and they kept nothing) re-derived by arithmetic in a second function that could not see it. That is the kind of coupling that is correct until the filter above it moves.

So it now counts the thing it means rather than inferring it:

```rust
let rendered = self.sources.len().saturating_sub(self.omitted);
let cut = self.sources[..rendered].iter().filter(|s| s.truncated()).count();
```

**Falsified before fixing**, since an unreachable-today bug is exactly the sort a test can pass for the wrong reason. `an_empty_omitted_source_does_not_hide_a_truncated_one` builds the report directly — one rendered source cut 40,000→31,900, one empty omitted row — and against the old `notice()` it fails with the operator-visible symptom rather than a count assertion:

> A step in this workflow was handed 40000 characters from 2 sources — … — so **1 of them could not be shown to it at all**, and the step ran on the 31900 characters that fitted.

31,900 characters were kept from a source that was truncated, and the sentence reports only the omission. With the fix it reads "1 of them were truncated and a further 1 could not be shown to it at all". Restored, and the other 19 tests in the module are unchanged and green.

Separately: this branch is now merged up to `main` (67dadf04). The two conflicts were `caps/mod.rs`, where `main`'s #881 blocked-node handling and this PR's #849 context-overflow rewrite both landed in `run_agent` and compose (the rewrite stays in the `map_err`, the block check follows it), and the vocabulary doc, where both sides appended a section.

**Comment by oxoxDev** [comment]
Merged `main` in (67dadf04) and fixed the CodeRabbit finding (f6f0d1c0). `mergeable` is back to `MERGEABLE`.

### The one red lane is `main`'s, not this branch's

`Rust (openhuman, tinycortex)` fails to **build**, with two errors that have nothing to do with #849:

```
error[E0063]: missing fields `approvals` and `blocked_nodes` in initializer of `ports::types::CompanyEvent`
  --> src/server/ops/workflows.rs:3699
error[E0063]: missing field `overlay_desk_tools` in initializer of `ports::types::CompanyRecord`
  --> src/workflows/blocked_node_test.rs:123
```

Both are struct literals on `main` that were never updated when `main` widened the structs beside them — `blocked_nodes`/`approvals` from fa846ede (#881/#880) and `overlay_desk_tools` from b019c5e4. This PR touches neither file, and neither `ports/types.rs`; its four files are the two `caps` modules, one test and one doc.

The same lane is already failing on `main` for the same two errors — [run 32000773552](https://github.com/tinyhumansai/opencompany/actions/runs/32000773552), `Rust (openhuman, tinycortex)`, `missing field overlay_desk_tools`. This branch inherited it by merging `main`; it did not introduce it, and it went red here only because the pre-merge base predated the breakage.

Deliberately **not** repaired here — it blocks every PR that merges `main`, so it wants its own PR to `main` rather than a drive-by on a feature branch. The repair is two lines (add the two `Vec::new()` fields; `overlay_desk_tools` is a `BTreeMap`, so `Default::default()`). Applied locally only to run this branch's gates, then reverted before pushing.

### Gates, with that local repair in place so the gated lane could build

```
cargo fmt --all -- --check                                              pass
cargo clippy --locked --all-targets -- -D warnings                      pass
cargo clippy --locked --no-deps --features openhuman,tinycortex \
  --all-targets -- -D warnings                                          pass
cargo test --locked                                    2533 passed, 0 failed
cargo check --locked --features openhuman,tinycortex --all-targets      pass
cargo test --locked --features openhuman,tinycortex --tests
                                       3902 + 24 passed, 0 failed
```

`workflows::caps::upstream` is 20/20, and every other lane on this PR is green.

One local-only note: `harness::brain::tests::a_cancelled_delegated_card_records_no_artifact` overflows the stack on a default macOS test thread and passes under `RUST_MIN_STACK=32M`. It predates this branch, which touches nothing it exercises. It passes on CI's runners — flagging it only so the next person running the gated suite on a laptop does not read it as a regression.

**Comment by M3gA-Mind** [comment]
Rebased onto current `main` (`9dc9971a`). The previous head failed **only** step 7,
*Build (openhuman, tinycortex)*, on a stale base — `E0063` for `approvals` /
`blocked_nodes` on `CompanyEvent` (`fa846ede`, #881/#880) and `overlay_desk_tools`
on `CompanyRecord` (`b019c5e4`). Every other lane was green and `mergeable` was
`MERGEABLE`, because git saw no textual conflict on a *merge* — only the compiler
saw the break, and only in the one lane that builds this code.

**No field was filled to silence the compiler.** All three construction sites belong
to `main`, not to this branch, so the rebase's three-way merge carried `main`'s own
values in on hunks these commits never touched. Stating the values explicitly rather
than leaving them implicit: `blocked_nodes` and `approvals` are one row per node
blocked / approval parked, and these fan-in tests park nothing, so empty is a true
receipt rather than an unset field; `overlay_desk_tools` empty means "no operator
override, the manifest decides", and these tests assert on the upstream budget, not
on desk tool ceilings.

**Two textual conflicts did surface during the replay** — a rebase replays each commit
onto the moved base, so it conflicts where a merge does not. One was mechanical (a
widened re-export list). The other was not: `caps/mod.rs` had both #881 and #849
rewriting the *same* statement, `main` changing it to `let (outcome, parked) = …` and
appending the blocked-node block, this branch rewriting the `map_err` to add
context-overflow advice. Taking either side wholesale would have silently deleted the
other's feature. Resolved by keeping `main`'s structure and destructuring **and** this
branch's `map_err`; both are verified present after the replay.

**@coderabbitai — the marker/separator budget fix survives the rebase intact.** The
post-rebase branch diff is byte-identical to the pre-rebase one apart from one blank
line between two doc sections. All three parts of the fix for the 243,886-characters-
under-a-32,000-character-budget finding are present and executing:

* **reservation** — `MAX_MARKER_CHARS = 320`, with `kept = allowance.saturating_sub(MAX_MARKER_CHARS)`
* **aggregation** — `max_rendered_sources(budget)`, sources past that limit folded into one line
* **derived cap** — the `clamp_to_budget` backstop

Verified running, not merely compiled: the gated lane executed 20 `workflows::caps::upstream::tests`,
including `a_thousand_oversized_sources_stay_inside_the_budget`, `no_marker_can_exceed_its_reserved_size`,
`a_truncation_marker_is_paid_for_by_its_own_source` and `the_backstop_is_never_what_enforces_the_budget`.

Local run of the exact lane that was failing, on the pushed commit:

| Command | Result |
| --- | --- |
| `cargo build --locked --features openhuman,tinycortex --all-targets` | exit 0 — no `E0063` |
| `cargo clippy --locked --no-deps --features openhuman,tinycortex --all-targets -- -D warnings` | exit 0 |
| `cargo test --locked --features openhuman,tinycortex --tests` | **4132 passed, 0 failed, 3 ignored** |
| `cargo fmt --all -- --check` | exit 0 |

@coderabbitai review
